apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sock-shop-tls
  namespace: sock-shop
spec:
  secretName: sock-shop-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: socks.oluwanifemiakintomide.me
  dnsNames:
  - socks.oluwanifemiakintomide.me
  - grafana.oluwanifemiakintomide.me
  - prometheus.oluwanifemiakintomide.me